### ISSUE TITLE
Button Component

### ISSUE THREAD

**Issue by tamilarasumk731** [Team-Tomato/Funkids#2]
Create different types of button component.
1. Button layout. The button should be dynamic. (Element ID, Size, Color, Hover Color, Function Callback, etc., These are the arguments should be passed to the constructor while creating a button)
2. The created component should be exportable.

**Comment by vsasvipul0605** [comment]
assign this issue to me

**Comment by tamilarasumk731** [comment]
@vsasvipul0605 Task assigned.

**Comment by InbasasiS** [comment]
Closing since the PR got merged
