### ISSUE TITLE
Card Component

### ISSUE THREAD

**Issue by tamilarasumk731** [Team-Tomato/Funkids#3]
Create a card layout.
1. The card should be dynamic.  (Element ID, Size, Color, Hover effect, Card content, etc., These are the arguments should be passed to the constructor while creating a card)
2. The created component should be exportable.

**Comment by anuradha9712** [comment]
assign this issue to me

**Comment by tamilarasumk731** [comment]
@anuradha9712 Task assigned 

cc: @AkbarHabeeb @InbasasiS @smartsri18

**Comment by AkbarHabeeb** [comment]
#25 closed
