### ISSUE TITLE
Header Component

### ISSUE THREAD

**Issue by tamilarasumk731** [Team-Tomato/Funkids#5]
1. Create a header component.
2. The constructor parameters are header content(logo, about us, contact us) along with the hyperlink.
3. The size and other necessary css properties are dynamic. These parameters should be passed along with the constructor. 
4. The component should be exportable.

**Comment by tamilarasumk731** [comment]
@anuradha9712 Assigning the task

**Comment by AkbarHabeeb** [comment]
#11 Closed
